# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QLayout, QMainWindow, QPushButton, QScrollArea,
    QSizePolicy, QSpacerItem, QToolButton, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1000, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1000, 600))
        MainWindow.setMaximumSize(QSize(1000, 600))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 10, 981, 581))
        self.horizontalLayout_main = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_main.setSpacing(5)
        self.horizontalLayout_main.setObjectName(u"horizontalLayout_main")
        self.horizontalLayout_main.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_main.setContentsMargins(0, 5, 0, 5)
        self.sideBar = QFrame(self.layoutWidget)
        self.sideBar.setObjectName(u"sideBar")
        sizePolicy.setHeightForWidth(self.sideBar.sizePolicy().hasHeightForWidth())
        self.sideBar.setSizePolicy(sizePolicy)
        self.sideBar.setMinimumSize(QSize(200, 555))
        self.sideBar.setMaximumSize(QSize(200, 555))
        self.sideBar.setFrameShape(QFrame.Shape.StyledPanel)
        self.sideBar.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayoutWidget_2 = QWidget(self.sideBar)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(10, 40, 181, 511))
        self.verticalLayout_sidebar = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_sidebar.setObjectName(u"verticalLayout_sidebar")
        self.verticalLayout_sidebar.setContentsMargins(0, 0, 0, 0)
        self.logoArea = QFrame(self.verticalLayoutWidget_2)
        self.logoArea.setObjectName(u"logoArea")
        self.logoArea.setEnabled(True)
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.logoArea.sizePolicy().hasHeightForWidth())
        self.logoArea.setSizePolicy(sizePolicy1)
        self.logoArea.setMaximumSize(QSize(200, 100))
        self.logoArea.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.logoArea.setFrameShape(QFrame.Shape.StyledPanel)
        self.logoArea.setFrameShadow(QFrame.Shadow.Raised)

        self.verticalLayout_sidebar.addWidget(self.logoArea)

        self.toggleSystem = QPushButton(self.verticalLayoutWidget_2)
        self.toggleSystem.setObjectName(u"toggleSystem")

        self.verticalLayout_sidebar.addWidget(self.toggleSystem)

        self.btnStart = QPushButton(self.verticalLayoutWidget_2)
        self.btnStart.setObjectName(u"btnStart")

        self.verticalLayout_sidebar.addWidget(self.btnStart)

        self.btnDashboard = QPushButton(self.verticalLayoutWidget_2)
        self.btnDashboard.setObjectName(u"btnDashboard")

        self.verticalLayout_sidebar.addWidget(self.btnDashboard)

        self.btnHistory = QPushButton(self.verticalLayoutWidget_2)
        self.btnHistory.setObjectName(u"btnHistory")

        self.verticalLayout_sidebar.addWidget(self.btnHistory)

        self.btnEmergency = QPushButton(self.verticalLayoutWidget_2)
        self.btnEmergency.setObjectName(u"btnEmergency")

        self.verticalLayout_sidebar.addWidget(self.btnEmergency)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)

        self.verticalLayout_sidebar.addItem(self.verticalSpacer)

        self.lblTime = QLabel(self.verticalLayoutWidget_2)
        self.lblTime.setObjectName(u"lblTime")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.lblTime.sizePolicy().hasHeightForWidth())
        self.lblTime.setSizePolicy(sizePolicy2)
        font = QFont()
        font.setFamilies([u"Consolas"])
        self.lblTime.setFont(font)
        self.lblTime.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_sidebar.addWidget(self.lblTime)


        self.horizontalLayout_main.addWidget(self.sideBar)

        self.mainContent = QFrame(self.layoutWidget)
        self.mainContent.setObjectName(u"mainContent")
        sizePolicy.setHeightForWidth(self.mainContent.sizePolicy().hasHeightForWidth())
        self.mainContent.setSizePolicy(sizePolicy)
        self.mainContent.setMinimumSize(QSize(770, 550))
        self.mainContent.setMaximumSize(QSize(770, 570))
        self.mainContent.setFrameShape(QFrame.Shape.StyledPanel)
        self.mainContent.setFrameShadow(QFrame.Shadow.Raised)
        self.layoutWidget_2 = QWidget(self.mainContent)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(-1, -16, 781, 591))
        self.contentArea = QVBoxLayout(self.layoutWidget_2)
        self.contentArea.setSpacing(0)
        self.contentArea.setObjectName(u"contentArea")
        self.contentArea.setContentsMargins(5, 0, 5, 0)
        self.mainPanel = QFrame(self.layoutWidget_2)
        self.mainPanel.setObjectName(u"mainPanel")
        sizePolicy.setHeightForWidth(self.mainPanel.sizePolicy().hasHeightForWidth())
        self.mainPanel.setSizePolicy(sizePolicy)
        self.mainPanel.setMinimumSize(QSize(770, 400))
        self.mainPanel.setMaximumSize(QSize(770, 390))
        self.mainPanel.setFrameShape(QFrame.Shape.StyledPanel)
        self.mainPanel.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayoutWidget = QWidget(self.mainPanel)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(0, 0, 771, 391))
        self.middleLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.middleLayout.setSpacing(5)
        self.middleLayout.setObjectName(u"middleLayout")
        self.middleLayout.setContentsMargins(0, 0, 0, 0)
        self.cameraContainer = QFrame(self.horizontalLayoutWidget)
        self.cameraContainer.setObjectName(u"cameraContainer")
        sizePolicy.setHeightForWidth(self.cameraContainer.sizePolicy().hasHeightForWidth())
        self.cameraContainer.setSizePolicy(sizePolicy)
        self.cameraContainer.setMinimumSize(QSize(400, 380))
        self.cameraContainer.setMaximumSize(QSize(400, 380))
        self.cameraContainer.setFrameShape(QFrame.Shape.StyledPanel)
        self.cameraContainer.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayoutWidget = QWidget(self.cameraContainer)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(0, 0, 401, 379))
        self.cameraLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.cameraLayout.setObjectName(u"cameraLayout")
        self.cameraLayout.setContentsMargins(0, 0, 0, 0)
        self.cameraLabelContainer = QFrame(self.verticalLayoutWidget)
        self.cameraLabelContainer.setObjectName(u"cameraLabelContainer")
        sizePolicy2.setHeightForWidth(self.cameraLabelContainer.sizePolicy().hasHeightForWidth())
        self.cameraLabelContainer.setSizePolicy(sizePolicy2)
        self.cameraLabelContainer.setMinimumSize(QSize(0, 30))
        self.cameraLabelContainer.setMaximumSize(QSize(16777215, 30))
        self.cameraLabelContainer.setFrameShape(QFrame.Shape.StyledPanel)
        self.cameraLabelContainer.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayoutWidget_2 = QWidget(self.cameraLabelContainer)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(0, 0, 341, 31))
        self.cameraLabelLayout = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.cameraLabelLayout.setObjectName(u"cameraLabelLayout")
        self.cameraLabelLayout.setContentsMargins(5, 0, 0, 0)
        self.cameraLabel = QLabel(self.horizontalLayoutWidget_2)
        self.cameraLabel.setObjectName(u"cameraLabel")
        font1 = QFont()
        font1.setFamilies([u"Consolas"])
        font1.setPointSize(10)
        self.cameraLabel.setFont(font1)

        self.cameraLabelLayout.addWidget(self.cameraLabel)


        self.cameraLayout.addWidget(self.cameraLabelContainer)

        self.cameraScreen = QFrame(self.verticalLayoutWidget)
        self.cameraScreen.setObjectName(u"cameraScreen")
        sizePolicy.setHeightForWidth(self.cameraScreen.sizePolicy().hasHeightForWidth())
        self.cameraScreen.setSizePolicy(sizePolicy)
        self.cameraScreen.setMinimumSize(QSize(390, 340))
        self.cameraScreen.setMaximumSize(QSize(390, 340))
        self.cameraScreen.setFrameShape(QFrame.Shape.StyledPanel)
        self.cameraScreen.setFrameShadow(QFrame.Shadow.Raised)
        self.cameraView = QLabel(self.cameraScreen)
        self.cameraView.setObjectName(u"cameraView")
        self.cameraView.setGeometry(QRect(10, 0, 381, 331))
        self.overlayPad = QFrame(self.cameraScreen)
        self.overlayPad.setObjectName(u"overlayPad")
        self.overlayPad.setGeometry(QRect(250, 200, 131, 111))
        self.overlayPad.setFrameShape(QFrame.Shape.StyledPanel)
        self.overlayPad.setFrameShadow(QFrame.Shadow.Raised)
        self.btnUp = QToolButton(self.overlayPad)
        self.btnUp.setObjectName(u"btnUp")
        self.btnUp.setGeometry(QRect(50, 10, 31, 26))
        self.btnLeft = QToolButton(self.overlayPad)
        self.btnLeft.setObjectName(u"btnLeft")
        self.btnLeft.setGeometry(QRect(20, 40, 31, 26))
        self.btnDown = QToolButton(self.overlayPad)
        self.btnDown.setObjectName(u"btnDown")
        self.btnDown.setGeometry(QRect(50, 70, 31, 26))
        self.btnRight = QToolButton(self.overlayPad)
        self.btnRight.setObjectName(u"btnRight")
        self.btnRight.setGeometry(QRect(80, 40, 31, 26))

        self.cameraLayout.addWidget(self.cameraScreen)


        self.middleLayout.addWidget(self.cameraContainer)

        self.analysisContainer = QFrame(self.horizontalLayoutWidget)
        self.analysisContainer.setObjectName(u"analysisContainer")
        sizePolicy.setHeightForWidth(self.analysisContainer.sizePolicy().hasHeightForWidth())
        self.analysisContainer.setSizePolicy(sizePolicy)
        self.analysisContainer.setMinimumSize(QSize(350, 380))
        self.analysisContainer.setMaximumSize(QSize(350, 380))
        self.analysisContainer.setFrameShape(QFrame.Shape.StyledPanel)
        self.analysisContainer.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayoutWidget_3 = QWidget(self.analysisContainer)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(0, 0, 2451, 379))
        self.analysisLayout = QVBoxLayout(self.verticalLayoutWidget_3)
        self.analysisLayout.setObjectName(u"analysisLayout")
        self.analysisLayout.setContentsMargins(0, 0, 0, 0)
        self.analysisLabelContainer = QFrame(self.verticalLayoutWidget_3)
        self.analysisLabelContainer.setObjectName(u"analysisLabelContainer")
        sizePolicy.setHeightForWidth(self.analysisLabelContainer.sizePolicy().hasHeightForWidth())
        self.analysisLabelContainer.setSizePolicy(sizePolicy)
        self.analysisLabelContainer.setMinimumSize(QSize(350, 30))
        self.analysisLabelContainer.setMaximumSize(QSize(350, 30))
        self.analysisLabelContainer.setFrameShape(QFrame.Shape.StyledPanel)
        self.analysisLabelContainer.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayoutWidget_6 = QWidget(self.analysisLabelContainer)
        self.horizontalLayoutWidget_6.setObjectName(u"horizontalLayoutWidget_6")
        self.horizontalLayoutWidget_6.setGeometry(QRect(0, 0, 351, 31))
        self.analysisLabelLayout = QHBoxLayout(self.horizontalLayoutWidget_6)
        self.analysisLabelLayout.setObjectName(u"analysisLabelLayout")
        self.analysisLabelLayout.setContentsMargins(5, 0, 10, 0)
        self.analysisLabel = QLabel(self.horizontalLayoutWidget_6)
        self.analysisLabel.setObjectName(u"analysisLabel")
        sizePolicy.setHeightForWidth(self.analysisLabel.sizePolicy().hasHeightForWidth())
        self.analysisLabel.setSizePolicy(sizePolicy)
        self.analysisLabel.setFont(font1)

        self.analysisLabelLayout.addWidget(self.analysisLabel)

        self.horizontalSpacer = QSpacerItem(80, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.analysisLabelLayout.addItem(self.horizontalSpacer)

        self.refreshBtn = QPushButton(self.horizontalLayoutWidget_6)
        self.refreshBtn.setObjectName(u"refreshBtn")
        sizePolicy.setHeightForWidth(self.refreshBtn.sizePolicy().hasHeightForWidth())
        self.refreshBtn.setSizePolicy(sizePolicy)
        self.refreshBtn.setMinimumSize(QSize(50, 25))
        self.refreshBtn.setMaximumSize(QSize(50, 25))

        self.analysisLabelLayout.addWidget(self.refreshBtn)


        self.analysisLayout.addWidget(self.analysisLabelContainer)

        self.analysisScroll = QScrollArea(self.verticalLayoutWidget_3)
        self.analysisScroll.setObjectName(u"analysisScroll")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.analysisScroll.sizePolicy().hasHeightForWidth())
        self.analysisScroll.setSizePolicy(sizePolicy3)
        self.analysisScroll.setMinimumSize(QSize(350, 340))
        self.analysisScroll.setMaximumSize(QSize(350, 340))
        self.analysisScroll.setWidgetResizable(True)
        self.analysisContent = QWidget()
        self.analysisContent.setObjectName(u"analysisContent")
        self.analysisContent.setGeometry(QRect(0, 0, 348, 338))
        self.analysisScroll.setWidget(self.analysisContent)

        self.analysisLayout.addWidget(self.analysisScroll)


        self.middleLayout.addWidget(self.analysisContainer)


        self.contentArea.addWidget(self.mainPanel)

        self.bottomPanel = QFrame(self.layoutWidget_2)
        self.bottomPanel.setObjectName(u"bottomPanel")
        sizePolicy.setHeightForWidth(self.bottomPanel.sizePolicy().hasHeightForWidth())
        self.bottomPanel.setSizePolicy(sizePolicy)
        self.bottomPanel.setMinimumSize(QSize(760, 170))
        self.bottomPanel.setMaximumSize(QSize(760, 170))
        self.bottomPanel.setFrameShape(QFrame.Shape.StyledPanel)
        self.bottomPanel.setFrameShadow(QFrame.Shadow.Raised)
        self.bottomLabelContainer = QFrame(self.bottomPanel)
        self.bottomLabelContainer.setObjectName(u"bottomLabelContainer")
        self.bottomLabelContainer.setGeometry(QRect(10, 0, 750, 40))
        sizePolicy.setHeightForWidth(self.bottomLabelContainer.sizePolicy().hasHeightForWidth())
        self.bottomLabelContainer.setSizePolicy(sizePolicy)
        self.bottomLabelContainer.setMinimumSize(QSize(750, 40))
        self.bottomLabelContainer.setMaximumSize(QSize(750, 40))
        self.bottomLabelContainer.setFrameShape(QFrame.Shape.StyledPanel)
        self.bottomLabelContainer.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayoutWidget_4 = QWidget(self.bottomLabelContainer)
        self.horizontalLayoutWidget_4.setObjectName(u"horizontalLayoutWidget_4")
        self.horizontalLayoutWidget_4.setGeometry(QRect(-1, 0, 741, 31))
        self.bottomLabelLayout = QHBoxLayout(self.horizontalLayoutWidget_4)
        self.bottomLabelLayout.setObjectName(u"bottomLabelLayout")
        self.bottomLabelLayout.setContentsMargins(0, 2, 0, 0)
        self.bottomLabel = QLabel(self.horizontalLayoutWidget_4)
        self.bottomLabel.setObjectName(u"bottomLabel")
        self.bottomLabel.setFont(font1)

        self.bottomLabelLayout.addWidget(self.bottomLabel)

        self.refreshHistoryBtn = QPushButton(self.horizontalLayoutWidget_4)
        self.refreshHistoryBtn.setObjectName(u"refreshHistoryBtn")
        sizePolicy.setHeightForWidth(self.refreshHistoryBtn.sizePolicy().hasHeightForWidth())
        self.refreshHistoryBtn.setSizePolicy(sizePolicy)
        self.refreshHistoryBtn.setMinimumSize(QSize(50, 25))
        self.refreshHistoryBtn.setMaximumSize(QSize(50, 25))

        self.bottomLabelLayout.addWidget(self.refreshHistoryBtn)

        self.bottomContainer = QFrame(self.bottomPanel)
        self.bottomContainer.setObjectName(u"bottomContainer")
        self.bottomContainer.setGeometry(QRect(0, 30, 750, 120))
        sizePolicy.setHeightForWidth(self.bottomContainer.sizePolicy().hasHeightForWidth())
        self.bottomContainer.setSizePolicy(sizePolicy)
        self.bottomContainer.setMinimumSize(QSize(750, 120))
        self.bottomContainer.setMaximumSize(QSize(760, 120))
        self.bottomContainer.setFrameShape(QFrame.Shape.StyledPanel)
        self.bottomContainer.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayoutWidget_3 = QWidget(self.bottomContainer)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(20, 10, 731, 111))
        self.bottomLayout = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.bottomLayout.setObjectName(u"bottomLayout")
        self.bottomLayout.setContentsMargins(5, 5, 5, 5)
        self.statusContainer = QFrame(self.horizontalLayoutWidget_3)
        self.statusContainer.setObjectName(u"statusContainer")
        self.statusContainer.setEnabled(False)
        sizePolicy.setHeightForWidth(self.statusContainer.sizePolicy().hasHeightForWidth())
        self.statusContainer.setSizePolicy(sizePolicy)
        self.statusContainer.setMinimumSize(QSize(150, 100))
        self.statusContainer.setMaximumSize(QSize(150, 100))
        self.statusContainer.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.statusContainer.setFrameShape(QFrame.Shape.NoFrame)
        self.statusContainer.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayoutWidget_4 = QWidget(self.statusContainer)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(0, 0, 141, 91))
        self.statusLayout = QVBoxLayout(self.verticalLayoutWidget_4)
        self.statusLayout.setObjectName(u"statusLayout")
        self.statusLayout.setContentsMargins(5, 0, 5, 0)
        self.statusLabel = QLabel(self.verticalLayoutWidget_4)
        self.statusLabel.setObjectName(u"statusLabel")
        self.statusLabel.setEnabled(False)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        self.statusLabel.setFont(font1)

        self.statusLayout.addWidget(self.statusLabel)

        self.lblAgvState = QLabel(self.verticalLayoutWidget_4)
        self.lblAgvState.setObjectName(u"lblAgvState")
        self.lblAgvState.setEnabled(False)
        sizePolicy2.setHeightForWidth(self.lblAgvState.sizePolicy().hasHeightForWidth())
        self.lblAgvState.setSizePolicy(sizePolicy2)
        self.lblAgvState.setFont(font)

        self.statusLayout.addWidget(self.lblAgvState)


        self.bottomLayout.addWidget(self.statusContainer)

        self.historyScroll = QScrollArea(self.horizontalLayoutWidget_3)
        self.historyScroll.setObjectName(u"historyScroll")
        sizePolicy3.setHeightForWidth(self.historyScroll.sizePolicy().hasHeightForWidth())
        self.historyScroll.setSizePolicy(sizePolicy3)
        self.historyScroll.setMinimumSize(QSize(0, 100))
        self.historyScroll.setMaximumSize(QSize(16777215, 100))
        self.historyScroll.setWidgetResizable(True)
        self.historyContent = QWidget()
        self.historyContent.setObjectName(u"historyContent")
        self.historyContent.setGeometry(QRect(0, 0, 562, 98))
        self.historyScroll.setWidget(self.historyContent)

        self.bottomLayout.addWidget(self.historyScroll)


        self.contentArea.addWidget(self.bottomPanel)


        self.horizontalLayout_main.addWidget(self.mainContent)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.toggleSystem.setText(QCoreApplication.translate("MainWindow", u"SYSTEM ON", None))
        self.btnStart.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.btnDashboard.setText(QCoreApplication.translate("MainWindow", u"Dashboard", None))
        self.btnHistory.setText(QCoreApplication.translate("MainWindow", u"History", None))
        self.btnEmergency.setText(QCoreApplication.translate("MainWindow", u"Emergency", None))
        self.lblTime.setText(QCoreApplication.translate("MainWindow", u"--:--:-- --:--", None))
        self.cameraLabel.setText(QCoreApplication.translate("MainWindow", u"AGV Control", None))
        self.cameraView.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.btnUp.setText(QCoreApplication.translate("MainWindow", u"\u25b3", None))
        self.btnLeft.setText(QCoreApplication.translate("MainWindow", u"\u25c1", None))
        self.btnDown.setText(QCoreApplication.translate("MainWindow", u"\u25bd", None))
        self.btnRight.setText(QCoreApplication.translate("MainWindow", u"\u25b7", None))
        self.analysisLabel.setText(QCoreApplication.translate("MainWindow", u"Analysis & Tasks", None))
        self.refreshBtn.setText(QCoreApplication.translate("MainWindow", u"\u27f3", None))
        self.bottomLabel.setText(QCoreApplication.translate("MainWindow", u"Status & History", None))
        self.refreshHistoryBtn.setText(QCoreApplication.translate("MainWindow", u"\u27f3", None))
        self.statusLabel.setText(QCoreApplication.translate("MainWindow", u"AGV Status", None))
        self.lblAgvState.setText(QCoreApplication.translate("MainWindow", u"status", None))
    # retranslateUi

